apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: playground
  namespace: dev
spec:
  entryPoints:
    - playground    # your custom entryPoint listening on port 8888
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: playground
          port: 8888

