apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: playground
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/playground`)
      services:
        - name: playground
          port: 8888
  tls:
    certResolver: default
